

version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - "/home/kml/docker_compose/index.html:/usr/share/nginx/html/index.html"
  app:
    image: httpd
    ports:
      - "8082:80"



